baseURL = "https://walissonaguirra.dev/"
languageCode = "pt-BR"
title = "Walisson Aguirra"
enableRobotsTXT = true

[params]
  description = "Engenheiro de software com foco em backend e arquitetura de aplicações, Go Lang e PHP"

  [params.author]
    author = "Walisson Aguirra"
    email  = "walissonaguirra@proton.me"

  [params.highlight.copy]
    enable = true
    display = "hover"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[menu]
  [[menu.main]]
    name = "Sobre"
    pageRef = "/sobre"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
  [markup.highlight]
    style = 'github'
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false

[params.giscus]
  repo            = "walissonaguirra/devpost"
  repoId          = "R_kgDOSHj-7g"          # obtenha em https://giscus.app/
  category        = "Announcements"         # opcional
  categoryId      = "DIC_kwDOSHj-7s4C7RLH"  # opcional, recomendado
  mapping         = "title"									# pathname | url | title | og:title | specific | number
  strict          = "0"											# "1" para exigir match estrito do título
  reactionsEnabled = "1"
  emitMetadata    = "0"
  inputPosition   = "bottom"                # bottom | top
  theme           = "light"
  lang            = "pt"
